/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIProject;

/**
 *
 * @author Masupik ID
 */
public class FrameData extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_MainMenu
     */
    public FrameData() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1Panel = new javax.swing.JPanel();
        background2Panel = new javax.swing.JPanel();
        background3Panel = new javax.swing.JPanel();
        idPenumpangLabel = new javax.swing.JLabel();
        namaPenumpangLabel = new javax.swing.JLabel();
        jurusanLabel = new javax.swing.JLabel();
        idPenumpang = new javax.swing.JTextField();
        namaPenumpang = new javax.swing.JTextField();
        jurusan = new javax.swing.JComboBox<>();
        titleFrame = new javax.swing.JLabel();
        tarifTiketLabel = new javax.swing.JLabel();
        jumlahBeliLabel = new javax.swing.JLabel();
        jumlahBayarLabel = new javax.swing.JLabel();
        tarifTiket = new javax.swing.JTextField();
        jumlahBayar = new javax.swing.JTextField();
        jumlahBeli = new javax.swing.JTextField();
        hitungButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1Panel.setBackground(new java.awt.Color(47, 43, 67));
        background1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 51, 81), 5));

        background2Panel.setBackground(new java.awt.Color(57, 51, 81));

        background3Panel.setBackground(new java.awt.Color(57, 51, 81));
        background3Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 43, 67), 3));

        idPenumpangLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idPenumpangLabel.setForeground(new java.awt.Color(255, 255, 255));
        idPenumpangLabel.setText("ID Penumpang");

        namaPenumpangLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaPenumpangLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaPenumpangLabel.setText("Nama Penumpang");

        jurusanLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jurusanLabel.setForeground(new java.awt.Color(255, 255, 255));
        jurusanLabel.setText("Jurusan");

        idPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPenumpangActionPerformed(evt);
            }
        });

        namaPenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPenumpangActionPerformed(evt);
            }
        });

        jurusan.setBackground(new java.awt.Color(102, 102, 102));
        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya-Malang", "Bandung-Jakarta", "Bekasi-Depok", "Semarang-Yogyakarta" }));

        titleFrame.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleFrame.setForeground(new java.awt.Color(255, 255, 255));
        titleFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleFrame.setText("APLIKASI TIKET BUS PULAU JAWA");

        tarifTiketLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tarifTiketLabel.setForeground(new java.awt.Color(255, 255, 255));
        tarifTiketLabel.setText("Tarif Tiket");

        jumlahBeliLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlahBeliLabel.setForeground(new java.awt.Color(255, 255, 255));
        jumlahBeliLabel.setText("Jumlah Beli");

        jumlahBayarLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumlahBayarLabel.setForeground(new java.awt.Color(255, 255, 255));
        jumlahBayarLabel.setText("Jumlah Bayar");

        tarifTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifTiketActionPerformed(evt);
            }
        });

        jumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBayarActionPerformed(evt);
            }
        });

        jumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBeliActionPerformed(evt);
            }
        });

        hitungButton.setBackground(new java.awt.Color(102, 102, 102));
        hitungButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hitungButton.setForeground(new java.awt.Color(255, 255, 255));
        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        simpanButton.setBackground(new java.awt.Color(102, 102, 102));
        simpanButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        simpanButton.setText("Simpan");
        simpanButton.setPreferredSize(new java.awt.Dimension(80, 20));
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(102, 102, 102));
        refreshButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setPreferredSize(new java.awt.Dimension(80, 20));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        hapusButton.setBackground(new java.awt.Color(102, 102, 102));
        hapusButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusButton.setText("Hapus");
        hapusButton.setPreferredSize(new java.awt.Dimension(80, 20));

        keluarButton.setBackground(new java.awt.Color(102, 102, 102));
        keluarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        keluarButton.setText("Keluar");
        keluarButton.setPreferredSize(new java.awt.Dimension(80, 20));

        javax.swing.GroupLayout background3PanelLayout = new javax.swing.GroupLayout(background3Panel);
        background3Panel.setLayout(background3PanelLayout);
        background3PanelLayout.setHorizontalGroup(
            background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(background3PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(background3PanelLayout.createSequentialGroup()
                        .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idPenumpangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaPenumpangLabel)
                            .addComponent(jurusanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaPenumpang)
                            .addComponent(jurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(background3PanelLayout.createSequentialGroup()
                                .addComponent(jumlahBayarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahBayar))
                            .addGroup(background3PanelLayout.createSequentialGroup()
                                .addComponent(tarifTiketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tarifTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background3PanelLayout.createSequentialGroup()
                                .addComponent(jumlahBeliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(background3PanelLayout.createSequentialGroup()
                        .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        background3PanelLayout.setVerticalGroup(
            background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPenumpangLabel)
                    .addComponent(idPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifTiketLabel)
                    .addComponent(tarifTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPenumpangLabel)
                    .addComponent(namaPenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBeliLabel)
                    .addComponent(jumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitungButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusanLabel)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBayarLabel)
                    .addComponent(jumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(background3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout background2PanelLayout = new javax.swing.GroupLayout(background2Panel);
        background2Panel.setLayout(background2PanelLayout);
        background2PanelLayout.setHorizontalGroup(
            background2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        background2PanelLayout.setVerticalGroup(
            background2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout background1PanelLayout = new javax.swing.GroupLayout(background1Panel);
        background1Panel.setLayout(background1PanelLayout);
        background1PanelLayout.setHorizontalGroup(
            background1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        background1PanelLayout.setVerticalGroup(
            background1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1PanelLayout.createSequentialGroup()
                .addComponent(background2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPenumpangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPenumpangActionPerformed

    private void idPenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPenumpangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPenumpangActionPerformed

    private void tarifTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifTiketActionPerformed

    private void jumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahBayarActionPerformed

    private void jumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahBeliActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        int varTarifTiket = Integer.parseInt(tarifTiket.getText());
        int varJumlahBeli = Integer.parseInt(jumlahBeli.getText());
        String varJumlahBayar = Integer.toString(varTarifTiket * varJumlahBeli);
        jumlahBayar.setText(varJumlahBayar);
    }//GEN-LAST:event_hitungButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background1Panel;
    private javax.swing.JPanel background2Panel;
    private javax.swing.JPanel background3Panel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton hitungButton;
    private javax.swing.JTextField idPenumpang;
    private javax.swing.JLabel idPenumpangLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahBayar;
    private javax.swing.JLabel jumlahBayarLabel;
    private javax.swing.JTextField jumlahBeli;
    private javax.swing.JLabel jumlahBeliLabel;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JLabel jurusanLabel;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTextField namaPenumpang;
    private javax.swing.JLabel namaPenumpangLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField tarifTiket;
    private javax.swing.JLabel tarifTiketLabel;
    private javax.swing.JLabel titleFrame;
    // End of variables declaration//GEN-END:variables
}
