/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIProject;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Masupik ID
 */
public class FrameMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMainMenu
     */
    public FrameMainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        homeSpacePanel = new javax.swing.JPanel();
        homeSpaceBackground = new javax.swing.JPanel();
        homeSpaceLabel = new javax.swing.JLabel();
        dev1Panel = new javax.swing.JPanel();
        dev1Label = new javax.swing.JLabel();
        dev2Panel = new javax.swing.JPanel();
        dev2Label = new javax.swing.JLabel();
        dev3Panel = new javax.swing.JPanel();
        dev3Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainMenuLabel = new javax.swing.JLabel();
        busButton = new javax.swing.JButton();
        keretaButton = new javax.swing.JButton();
        pesawatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuPanel.setBackground(new java.awt.Color(47, 43, 67));

        homeSpacePanel.setBackground(new java.awt.Color(57, 51, 81));

        homeSpaceBackground.setBackground(new java.awt.Color(255, 102, 0));
        homeSpaceBackground.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), javax.swing.BorderFactory.createCompoundBorder())));

        homeSpaceLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 22)); // NOI18N
        homeSpaceLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeSpaceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeSpaceLabel.setText("Home Space");

        javax.swing.GroupLayout homeSpaceBackgroundLayout = new javax.swing.GroupLayout(homeSpaceBackground);
        homeSpaceBackground.setLayout(homeSpaceBackgroundLayout);
        homeSpaceBackgroundLayout.setHorizontalGroup(
            homeSpaceBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeSpaceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        homeSpaceBackgroundLayout.setVerticalGroup(
            homeSpaceBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeSpaceBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeSpaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dev1Panel.setBackground(new java.awt.Color(57, 51, 81));
        dev1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        dev1Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dev1Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dev1PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dev1PanelMouseExited(evt);
            }
        });

        dev1Label.setForeground(new java.awt.Color(255, 255, 255));
        dev1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dev1Label.setText("Dev1");

        javax.swing.GroupLayout dev1PanelLayout = new javax.swing.GroupLayout(dev1Panel);
        dev1Panel.setLayout(dev1PanelLayout);
        dev1PanelLayout.setHorizontalGroup(
            dev1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dev1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dev1PanelLayout.setVerticalGroup(
            dev1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dev1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        dev2Panel.setBackground(new java.awt.Color(57, 51, 81));
        dev2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        dev2Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dev2PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dev2PanelMouseExited(evt);
            }
        });

        dev2Label.setForeground(new java.awt.Color(255, 255, 255));
        dev2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dev2Label.setText("Dev2");

        javax.swing.GroupLayout dev2PanelLayout = new javax.swing.GroupLayout(dev2Panel);
        dev2Panel.setLayout(dev2PanelLayout);
        dev2PanelLayout.setHorizontalGroup(
            dev2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dev2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dev2PanelLayout.setVerticalGroup(
            dev2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dev2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        dev3Panel.setBackground(new java.awt.Color(57, 51, 81));
        dev3Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        dev3Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dev3PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dev3PanelMouseExited(evt);
            }
        });

        dev3Label.setForeground(new java.awt.Color(255, 255, 255));
        dev3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dev3Label.setText("Dev3");

        javax.swing.GroupLayout dev3PanelLayout = new javax.swing.GroupLayout(dev3Panel);
        dev3Panel.setLayout(dev3PanelLayout);
        dev3PanelLayout.setHorizontalGroup(
            dev3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dev3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dev3PanelLayout.setVerticalGroup(
            dev3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dev3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout homeSpacePanelLayout = new javax.swing.GroupLayout(homeSpacePanel);
        homeSpacePanel.setLayout(homeSpacePanelLayout);
        homeSpacePanelLayout.setHorizontalGroup(
            homeSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeSpaceBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dev1Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dev2Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dev3Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeSpacePanelLayout.setVerticalGroup(
            homeSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeSpacePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(homeSpaceBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(dev1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dev2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dev3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        mainMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        mainMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuLabel.setText("MAIN MENU");

        busButton.setBackground(new java.awt.Color(51, 51, 51));
        busButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        busButton.setForeground(new java.awt.Color(255, 255, 255));
        busButton.setText("TIKET BUS PULAU JAWA");
        busButton.setPreferredSize(new java.awt.Dimension(305, 38));
        busButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busButtonActionPerformed(evt);
            }
        });

        keretaButton.setBackground(new java.awt.Color(51, 51, 51));
        keretaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        keretaButton.setForeground(new java.awt.Color(255, 255, 255));
        keretaButton.setText("TIKET KERETA PULAU JAWA");
        keretaButton.setPreferredSize(new java.awt.Dimension(305, 38));
        keretaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keretaButtonMouseEntered(evt);
            }
        });
        keretaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keretaButtonActionPerformed(evt);
            }
        });

        pesawatButton.setBackground(new java.awt.Color(51, 51, 51));
        pesawatButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pesawatButton.setForeground(new java.awt.Color(255, 255, 255));
        pesawatButton.setText("TIKET PESAWAT PULAU JAWA");
        pesawatButton.setPreferredSize(new java.awt.Dimension(305, 38));
        pesawatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesawatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addComponent(homeSpacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(busButton, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keretaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesawatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeSpacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(busButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(keretaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pesawatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dev1PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dev1PanelMouseEntered
        dev1Panel.setBackground(new Color(47,43,67));
        dev1Panel.setBorder(new LineBorder(new Color(47,43,67), 2, true));
    }//GEN-LAST:event_dev1PanelMouseEntered

    private void dev1PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dev1PanelMouseExited
        dev1Panel.setBackground(new Color(57,51,81));
        dev1Panel.setBorder(new LineBorder(new Color(255,102,0), 2, true));
    }//GEN-LAST:event_dev1PanelMouseExited

    private void dev2PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dev2PanelMouseEntered
        dev2Panel.setBackground(new Color(47,43,67));
        dev2Panel.setBorder(new LineBorder(new Color(47,43,67), 2, true));
    }//GEN-LAST:event_dev2PanelMouseEntered

    private void dev2PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dev2PanelMouseExited
        dev2Panel.setBackground(new Color(57,51,81));
        dev2Panel.setBorder(new LineBorder(new Color(255,102,0), 2, true));
    }//GEN-LAST:event_dev2PanelMouseExited

    private void dev3PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dev3PanelMouseEntered
        dev3Panel.setBackground(new Color(47,43,67));
        dev3Panel.setBorder(new LineBorder(new Color(47,43,67), 2, true));
    }//GEN-LAST:event_dev3PanelMouseEntered

    private void dev3PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dev3PanelMouseExited
        dev3Panel.setBackground(new Color(57,51,81));
        dev3Panel.setBorder(new LineBorder(new Color(255,102,0), 2, true));
    }//GEN-LAST:event_dev3PanelMouseExited

    private void pesawatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesawatButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Maintenance in Progress", "Warning", 0);
    }//GEN-LAST:event_pesawatButtonActionPerformed

    private void keretaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keretaButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Maintenance in Progress", "Warning", 0);
    }//GEN-LAST:event_keretaButtonActionPerformed

    private void busButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busButtonActionPerformed
        new FrameData().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_busButtonActionPerformed

    private void keretaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keretaButtonMouseEntered
        
    }//GEN-LAST:event_keretaButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busButton;
    private javax.swing.JLabel dev1Label;
    private javax.swing.JPanel dev1Panel;
    private javax.swing.JLabel dev2Label;
    private javax.swing.JPanel dev2Panel;
    private javax.swing.JLabel dev3Label;
    private javax.swing.JPanel dev3Panel;
    private javax.swing.JPanel homeSpaceBackground;
    private javax.swing.JLabel homeSpaceLabel;
    private javax.swing.JPanel homeSpacePanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton keretaButton;
    private javax.swing.JLabel mainMenuLabel;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton pesawatButton;
    // End of variables declaration//GEN-END:variables
}
